/**
 * Nemotron 3 Super's output on the Northstar "crashing" pack (development data), recorded live on
 * September 27, 2026. It failed grounding in 4 of 8 passes, byte-identical each time: four quotes
 * omit their "Name: " speaker label, so the owner was not in the cited text.
 */
export const RECORDED_UNLABELLED_EXTRACTION = "{\"commitments\": [{\"id\": \"CMT-01\", \"featureId\": \"audit-export\", \"title\": \"Audit log export availability\", \"owner\": \"Maya Chen\", \"dueDate\": \"2026-09-14\", \"intent\": \"committed\", \"evidence\": [{\"sourceId\": \"SRC-01\", \"quote\": \"I will make audit log export available to Northstar by 2026-09-14.\"}]}, {\"id\": \"CMT-02\", \"featureId\": \"eu-residency\", \"title\": \"EU data residency\", \"owner\": \"Theo Park\", \"dueDate\": \"2026-09-18\", \"intent\": \"committed\", \"evidence\": [{\"sourceId\": \"SRC-01\", \"quote\": \"I commit to EU data residency for Northstar by 2026-09-18.\"}]}, {\"id\": \"CMT-03\", \"featureId\": \"usage-report\", \"title\": \"Weekly usage report delivery\", \"owner\": \"Maya Chen\", \"dueDate\": \"2026-09-11\", \"intent\": \"committed\", \"evidence\": [{\"sourceId\": \"SRC-01\", \"quote\": \"I will deliver the weekly usage report to Northstar by 2026-09-11.\"}]}, {\"id\": \"CMT-04\", \"featureId\": \"dashboard\", \"title\": \"Custom dashboard exploration\", \"owner\": null, \"dueDate\": null, \"intent\": \"tentative\", \"evidence\": [{\"sourceId\": \"SRC-01\", \"quote\": \"A custom dashboard would be interesting. Can we explore that next quarter? No commitment or date agreed.\"}]}, {\"id\": \"CMT-05\", \"featureId\": \"scim\", \"title\": \"SCIM provisioning availability\", \"owner\": \"Jon Bell\", \"dueDate\": \"2026-09-16\", \"intent\": \"committed\", \"evidence\": [{\"sourceId\": \"SRC-01\", \"quote\": \"I will make SCIM provisioning available to Northstar by 2026-09-16.\"}]}, {\"id\": \"CMT-06\", \"featureId\": \"saml\", \"title\": \"SAML SSO availability\", \"owner\": \"Jon Bell\", \"dueDate\": \"2026-09-10\", \"intent\": \"committed\", \"evidence\": [{\"sourceId\": \"SRC-06\", \"quote\": \"Jon Bell: I committed to SAML SSO for Northstar by 2026-09-10.\"}]}]}";

/** Recorded September 27 (crashing pack, pass 8 of 10 after the speaker-label fix): SAML's exact quote attributed to SRC-04; it is in SRC-06. */
export const RECORDED_MISATTRIBUTED_EXTRACTION = "{\"commitments\": [{\"id\": \"CMT-01\", \"featureId\": \"audit-export\", \"title\": \"Audit log export availability\", \"owner\": \"Maya Chen\", \"dueDate\": \"2026-09-14\", \"intent\": \"committed\", \"evidence\": [{\"sourceId\": \"SRC-01\", \"quote\": \"Maya Chen: I will make audit log export available to Northstar by 2026-09-14.\"}]}, {\"id\": \"CMT-02\", \"featureId\": \"eu-residency\", \"title\": \"EU data residency commitment\", \"owner\": \"Theo Park\", \"dueDate\": \"2026-09-18\", \"intent\": \"committed\", \"evidence\": [{\"sourceId\": \"SRC-01\", \"quote\": \"Theo Park: I commit to EU data residency for Northstar by 2026-09-18.\"}]}, {\"id\": \"CMT-03\", \"featureId\": \"usage-report\", \"title\": \"Weekly usage report delivery\", \"owner\": \"Maya Chen\", \"dueDate\": \"2026-09-11\", \"intent\": \"committed\", \"evidence\": [{\"sourceId\": \"SRC-01\", \"quote\": \"Maya Chen: I will deliver the weekly usage report to Northstar by 2026-09-11.\"}]}, {\"id\": \"CMT-04\", \"featureId\": \"scim\", \"title\": \"SCIM provisioning availability\", \"owner\": \"Jon Bell\", \"dueDate\": \"2026-09-16\", \"intent\": \"committed\", \"evidence\": [{\"sourceId\": \"SRC-01\", \"quote\": \"Jon Bell: I will make SCIM provisioning available to Northstar by 2026-09-16.\"}]}, {\"id\": \"CMT-05\", \"featureId\": \"dashboard\", \"title\": \"Custom dashboard exploration\", \"owner\": null, \"dueDate\": null, \"intent\": \"tentative\", \"evidence\": [{\"sourceId\": \"SRC-01\", \"quote\": \"No commitment or date agreed.\"}]}, {\"id\": \"CMT-06\", \"featureId\": \"saml\", \"title\": \"SAML SSO commitment\", \"owner\": \"Jon Bell\", \"dueDate\": \"2026-09-10\", \"intent\": \"committed\", \"evidence\": [{\"sourceId\": \"SRC-04\", \"quote\": \"Jon Bell: I committed to SAML SSO for Northstar by 2026-09-10.\"}]}]}";
